services:
  - type: web
    name: bodaboda-web
    runtime: python
    runtimeVersion: 3.11
    rootDir: bodaboda_web
    startCommand: gunicorn bodaboda_web.wsgi:application --log-file - --access-logfile - --workers 2
    buildCommand: python manage.py migrate && python manage.py collectstatic --noinput
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bodaboda_web.settings.prod
      - key: DEBUG
        value: "0"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
    plan: free
