pluginManagement {
    repositories {
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url uri('/tmp/local-maven') }
        google()
        mavenCentral()
    }
}

rootProject.name = "BodaAU"
include(":app")
