# Generated by Django 5.1.6 on 2026-04-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_location_stationrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visitevent',
            new_name='core_visite_event_t_75a026_idx',
            old_name='core_visitevent_event_t_4f0521_idx',
        ),
        migrations.RenameIndex(
            model_name='visitevent',
            new_name='core_visite_user_id_af7dc9_idx',
            old_name='core_visitevent_user_id_2ec0e6_idx',
        ),
    ]
