# Generated by Django 5.1.6 on 2026-05-02 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pushdevicetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('commission', 'Commission Charge'), ('settlement', 'Settlement Payment'), ('adjustment', 'Admin Adjustment')], max_length=20)),
                ('amount_tzs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='pushdevicetoken',
            new_name='core_pushde_user_id_381f08_idx',
            old_name='core_push_user_act_0c7b53_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdevicetoken',
            new_name='core_pushde_platfor_493ecf_idx',
            old_name='core_push_platf_0f0a40_idx',
        ),
        migrations.AddField(
            model_name='driverledgerentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_ledger_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverledgerentry',
            name='driver_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.driverprofile'),
        ),
        migrations.AddField(
            model_name='driverledgerentry',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.ride'),
        ),
    ]
